### ISSUE TITLE
Improving README

### ISSUE THREAD

**Issue by dmateusp** [munnellg/OfMagesAndMagic#2]
The description of the README does not describe how to use the application or how to get started, it should be improved to make it accessible

**Comment by dmateusp** [comment]
see #5

**Comment by munnellg** [comment]
Agreed! This is a huge weakness. It will be later in the week before I can get the time to write this properly. 

There is some literature around the spell system, combat system and element choices for the game which I wrote as part of the program, but it is not part of this repository. All of this will need to be aggregated and compiled into a single teaching document.

The project for doing this is on ShareLatex at the moment but could be moved here if that is what collaborators would prefer

**Comment by coolharsh55** [comment]
For starters, how to get it up and running. Something like, download, install using requirements.txt, run using python game.py (or something). And then how it should look or work, where to put the bot files, etc.

Also needs a good wiki (style) description of how everything is structured and modeled (or moduled :P )

**Comment by munnellg** [comment]
Daniel seems to have covered the bases with regards to requirements.txt, and how to run the game. Adding information about setting up battles and organizing teams will have to be my job. I'll get that done ASAP.

**Comment by munnellg** [comment]
README has been extended with simple bot tutorial, team setup tutorial. Any startup information beyond this should be relegated to a dedicated tutorial file
