### ISSUE TITLE
Adding compatibility with Python3

### ISSUE THREAD

**Issue by dmateusp** [munnellg/OfMagesAndMagic#6]
Compatibility with Python3 could be provided on a branch called "python3"

**Comment by dmateusp** [comment]
Code is ready for compatibility with Python3, can you create a new branch called "python3"? @munnellg

**Comment by munnellg** [comment]
python3 branch has been set up. Feel free to make a pull request there.

**Comment by munnellg** [comment]
Pull completed. Closing.
